"use client";
import { useEffect, useRef } from "react";
import * as THREE from "three";

export function GlobeScene(){
  const mount=useRef<HTMLDivElement>(null);
  useEffect(()=>{
    const host=mount.current;if(!host||!window.WebGLRenderingContext)return;
    const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(34,1,.1,100);camera.position.z=8.4;
    const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,powerPreference:"high-performance"});renderer.setPixelRatio(Math.min(devicePixelRatio,1.75));renderer.setClearColor(0,0);renderer.outputColorSpace=THREE.SRGBColorSpace;host.appendChild(renderer.domElement);
    const world=new THREE.Group();world.position.x=1.15;scene.add(world);
    const inner=new THREE.Mesh(new THREE.SphereGeometry(2.01,48,36),new THREE.MeshBasicMaterial({color:0x001127,transparent:true,opacity:.84}));world.add(inner);
    const globe=new THREE.Mesh(new THREE.SphereGeometry(2.06,48,32),new THREE.MeshBasicMaterial({color:0x087bff,wireframe:true,transparent:true,opacity:.36}));world.add(globe);
    const glow=new THREE.Mesh(new THREE.SphereGeometry(2.16,44,32),new THREE.ShaderMaterial({transparent:true,side:THREE.BackSide,blending:THREE.AdditiveBlending,uniforms:{glowColor:{value:new THREE.Color(0x0787ff)},viewVector:{value:camera.position}},vertexShader:`varying float i;uniform vec3 viewVector;void main(){vec3 n=normalize(normalMatrix*normal);vec3 v=normalize(normalMatrix*viewVector);i=pow(.68-dot(n,v),3.2);gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}`,fragmentShader:`varying float i;uniform vec3 glowColor;void main(){gl_FragColor=vec4(glowColor,i*.75);}`}));world.add(glow);
    const dots:number[]=[];for(let n=0;n<1050;n++){const p=Math.acos(2*Math.random()-1),t=Math.random()*Math.PI*2,r=2.03;dots.push(r*Math.sin(p)*Math.cos(t),r*Math.cos(p),r*Math.sin(p)*Math.sin(t))}const dotGeo=new THREE.BufferGeometry();dotGeo.setAttribute("position",new THREE.Float32BufferAttribute(dots,3));const cloud=new THREE.Points(dotGeo,new THREE.PointsMaterial({color:0x69baff,size:.018,transparent:true,opacity:.85,blending:THREE.AdditiveBlending}));world.add(cloud);
    const runners:{line:THREE.Line;dot:THREE.Mesh;rx:number;ry:number;speed:number;offset:number}[]=[];[[.25,.15,.15],[-.55,.3,.7],[.75,-.2,-.4],[1.1,.12,.5],[-.95,-.3,-.2]].forEach((rot,k)=>{const rx=3.15+k*.08,ry=1.48+k*.04,curve=new THREE.EllipseCurve(0,0,rx,ry,0,Math.PI*2),geo=new THREE.BufferGeometry().setFromPoints(curve.getPoints(180).map(p=>new THREE.Vector3(p.x,p.y,0))),line=new THREE.Line(geo,new THREE.LineBasicMaterial({color:k%2?0x207cdf:0x96cfff,transparent:true,opacity:.32,blending:THREE.AdditiveBlending}));line.rotation.set(rot[0],rot[1],rot[2]);world.add(line);const dot=new THREE.Mesh(new THREE.SphereGeometry(.035,10,10),new THREE.MeshBasicMaterial({color:0xd7edff}));world.add(dot);runners.push({line,dot,rx,ry,speed:.045+k*.012,offset:k/5})});
    const c=document.createElement("canvas");c.width=c.height=256;const cx=c.getContext("2d")!,grad=cx.createRadialGradient(128,128,4,128,128,128);grad.addColorStop(0,"rgba(0,125,255,.3)");grad.addColorStop(.42,"rgba(0,105,255,.12)");grad.addColorStop(1,"rgba(0,70,255,0)");cx.fillStyle=grad;cx.fillRect(0,0,256,256);const halo=new THREE.Sprite(new THREE.SpriteMaterial({map:new THREE.CanvasTexture(c),transparent:true,blending:THREE.AdditiveBlending,depthWrite:false}));halo.scale.set(6.2,6.2,1);halo.position.z=-.45;world.add(halo);
    const starPos:number[]=[];for(let n=0;n<160;n++)starPos.push((Math.random()-.5)*15,(Math.random()-.5)*9,(Math.random()-.5)*5-2);const starGeo=new THREE.BufferGeometry();starGeo.setAttribute("position",new THREE.Float32BufferAttribute(starPos,3));scene.add(new THREE.Points(starGeo,new THREE.PointsMaterial({color:0x147fff,size:.018,transparent:true,opacity:.6})));
    const pointer=new THREE.Vector2(),target=new THREE.Vector2(),onPointer=(e:PointerEvent)=>{target.x=(e.clientX/innerWidth-.5)*.42;target.y=(e.clientY/innerHeight-.5)*.22};window.addEventListener("pointermove",onPointer,{passive:true});
    const resize=()=>{const{width,height}=host.getBoundingClientRect();renderer.setSize(width,height,false);camera.aspect=width/Math.max(height,1);camera.updateProjectionMatrix();world.position.x=width<760?.55:1.15},observer=new ResizeObserver(resize);observer.observe(host);resize();
    const reduced=matchMedia("(prefers-reduced-motion: reduce)").matches,clock=new THREE.Clock();let frame=0;const loop=()=>{const t=clock.getElapsedTime();pointer.lerp(target,.035);if(!reduced){globe.rotation.y=t*.075;globe.rotation.x=Math.sin(t*.16)*.07;cloud.rotation.y=-t*.028;world.rotation.y+=(pointer.x-world.rotation.y)*.025;world.rotation.x+=(-pointer.y-world.rotation.x)*.025;runners.forEach((o,k)=>{const a=(t*o.speed+o.offset)*Math.PI*2,v=new THREE.Vector3(Math.cos(a)*o.rx,Math.sin(a)*o.ry,0);v.applyEuler(o.line.rotation);o.dot.position.copy(v);o.dot.scale.setScalar(1+Math.sin(t*3+k)*.35)})}renderer.render(scene,camera);frame=requestAnimationFrame(loop)};loop();
    return()=>{cancelAnimationFrame(frame);observer.disconnect();removeEventListener("pointermove",onPointer);scene.traverse(o=>{if(o instanceof THREE.Mesh||o instanceof THREE.Line||o instanceof THREE.Points){o.geometry?.dispose();const m=o.material;Array.isArray(m)?m.forEach(x=>x.dispose()):m?.dispose()}});renderer.dispose();renderer.domElement.remove()};
  },[]);
  return <div ref={mount} className="globe-scene" aria-hidden="true"/>;
}
