"use client";
import Link from "next/link";
import { useState } from "react";
import { GlobeScene } from "./GlobeScene";

const method=[{n:"I",title:"Diagnose",text:"Find the operational constraint that is limiting the value of your traction."},{n:"II",title:"Design",text:"Create the data, workflow, and AI blueprint around measurable business outcomes."},{n:"III",title:"Build",text:"Deploy the system, connect the stack, and give your team the context to run it."},{n:"IV",title:"Multiply",text:"Measure the lift, optimize adoption, and compound growth with each new signal."}];
const outcomes=[["+25%","Revenue in 90 days"],["10×","AI tool ROI"],["−40%","Operating costs"],["1M+","Impressions in 30 days"]];

function Arrow(){return <span aria-hidden="true">↗</span>}
function Header(){const[open,setOpen]=useState(false);return <header className="cf-header"><Link href="/" className="cf-logo"><i>I</i>IAN</Link><nav className={open?"cf-nav open":"cf-nav"}><Link href="#method">Method</Link><Link href="#systems">Systems</Link><Link href="/case-studies">Results</Link><Link href="/insights">Insights</Link><Link href="/about">Company</Link></nav><Link href="/assessment" className="cf-run">Get assessed <Arrow/></Link><button onClick={()=>setOpen(!open)} className="cf-menu" aria-label="Toggle menu">•••</button></header>}

function MiniOS(){return <div className="mini-os"><aside><b>IAN</b><span>Overview</span><span>Operations</span><span>Intelligence</span><span>Growth</span><span>Systems</span><small>COMPANY</small><span>Team</span><span>Knowledge</span></aside><div className="os-main"><div className="os-top"><span>Good morning, Alex</span><button>+ New initiative</button></div><div className="os-stats"><div><small>OPERATING LEVERAGE</small><b>4.8×</b><em>↑ 38%</em></div><div><small>FOUNDER DEPENDENCY</small><b>27%</b><em>↓ 41%</em></div><div><small>AI READINESS</small><b>82</b><em>High</em></div></div><div className="os-grid"><div className="os-chart"><span>BUSINESS VELOCITY</span><div className="bars">{[32,46,38,57,62,55,78,71,89,94].map((h,i)=><i key={i} style={{height:h+"%"}}/>)}</div><small>JAN&nbsp;&nbsp;&nbsp; FEB&nbsp;&nbsp;&nbsp; MAR&nbsp;&nbsp;&nbsp; APR&nbsp;&nbsp;&nbsp; MAY</small></div><div className="os-tasks"><span>ACTIVE SYSTEMS</span><p><i className="green"/> Lead qualification agent <b>Live</b></p><p><i className="blue"/> Executive signal brief <b>Daily</b></p><p><i className="orange"/> Margin anomaly monitor <b>Review</b></p></div></div></div></div>}

export default function Home(){return <main className="cf-site"><Header/>
  <section className="cf-hero"><div className="task-chip chip-a"><i>✓</i><span>System deployed<small>Revenue intelligence</small></span></div><div className="task-chip chip-b"><i>↗</i><span>Signal detected<small>Margin opportunity</small></span></div><div className="task-chip chip-c"><i>✓</i><span>Workflow optimized<small>12 hours recovered</small></span></div><GlobeScene/><div className="cf-hero-copy"><span className="cf-kicker">AI EXECUTION FOR COMPANIES WITH TRACTION</span><h1>Turn traction into<br/>intelligent scale</h1><p>IAN redesigns operations, integrates AI, and builds the growth systems that help founder-led companies move faster.</p><div><Link href="/assessment" className="cf-btn light">Get your scale roadmap <Arrow/></Link><Link href="/case-studies" className="cf-link">See client results</Link></div></div><div className="cf-scroll">Scroll to explore <span>↓</span></div></section>

  <section className="cf-proof"><div className="logo-row"><span>Selected team experience</span>{["NFL ALUMNI","DEFENSE","NETFLIX","UNIVERSAL","LLOYD’S","GENERAL MOTORS"].map(x=><b key={x}>{x}</b>)}</div><div className="proof-note"><div className="avatars"><i>A</i><i>M</i><i>C</i><i>+</i></div><p><b>Built for companies already in motion.</b><br/>Strategy, systems, and execution in one senior team.</p></div></section>

  <section className="cf-statement"><span className="cf-section-no">01 / WHAT IAN IS</span><h2>IAN is an AI execution partner<br/><em>designed to help ambitious companies scale.</em></h2><p>Most advisors stop at the deck. Most builders stop at the brief. We stay close enough to connect strategy, implementation, adoption, and measurable lift.</p></section>

  <section className="cf-platform" id="systems"><div className="platform-copy"><span className="cf-section-no">THE INTELLIGENT COMPANY SYSTEM</span><h2>Your company,<br/>with leverage built in.</h2><p>Bring the disconnected parts of your operation into one intelligent model. See what is happening, know what matters, and move the right work forward.</p><div className="feature-list"><p><i>01</i><b>Live operating context</b><span>One source of truth across data, decisions, and active work.</span></p><p><i>02</i><b>Human-approved intelligence</b><span>AI moves work forward while critical decisions stay with your team.</span></p><p><i>03</i><b>Systems that compound</b><span>Each workflow creates better context for the next one.</span></p></div><Link href="/services/operational-leverage" className="cf-btn dark">Explore operational leverage <Arrow/></Link></div><MiniOS/></section>

  <section className="cf-method" id="method"><div className="method-intro"><span className="cf-section-no">02 / THE METHOD</span><h2>Learn how to build<br/>an intelligent company.</h2><p>A practical sequence from operating constraint to scalable system.</p><Link href="/method" className="cf-link dark-link">Explore the full method <Arrow/></Link></div><div className="method-cards">{method.map((m,i)=><Link href="/method" className={`method-card mc-${i+1}`} key={m.n}><span>Chapter {i+1}</span><h3>{m.title}</h3><p>{m.text}</p><footer><i>{m.n}</i><b>THE FORCE MULTIPLIER METHOD</b><em>Read chapter ↗</em></footer></Link>)}</div></section>

  <section className="cf-work"><div className="work-heading"><span className="cf-section-no">03 / THREE MULTIPLIERS</span><h2>Build the company behind the growth.</h2><p>Choose the constraint that matters first. IAN connects the work across operations, growth, and venture execution.</p></div><article className="work-row"><div><small>01 / OPERATIONS</small><h3>Make your business<br/>think and move.</h3><p>Connect your data, automate high-friction workflows, and give leaders real-time decision signals.</p><Link href="/services/operational-leverage">Explore AI systems <Arrow/></Link></div><div className="workflow-ui"><header><span>New intelligence workflow</span><b>Live</b></header><div className="flow-node main-node"><i>IAN</i><span>Margin intelligence<small>Analyze weekly performance</small></span></div><div className="flow-line"/><div className="flow-branches"><span>Financial data</span><span>CRM signals</span><span>Team context</span></div><footer><span>Last run: 2 min ago</span><b>3 opportunities found</b></footer></div></article><article className="work-row reverse"><div><small>02 / GROWTH</small><h3>Turn expertise<br/>into attention.</h3><p>Build founder positioning, creative production, and distribution systems that compound instead of disappearing between campaigns.</p><Link href="/services/growth-leverage">Explore growth systems <Arrow/></Link></div><div className="content-ui"><header><span>FOUNDER VISIBILITY ENGINE</span><button>Running</button></header><div className="content-score"><span>Weekly reach</span><b>248.6K</b><em>+34.2%</em></div><div className="content-chart"><i/><i/><i/><i/><i/><i/><i/><i/><i/><i/><i/><i/></div><div className="content-foot"><span>Authority</span><span>Distribution</span><span>Inbound</span></div></div></article><article className="work-row"><div><small>03 / VENTURE</small><h3>Compress years<br/>into months.</h3><p>Access senior operators, strategic partnerships, visibility, and capital readiness through the IAN ecosystem.</p><Link href="/accelerator">Explore the accelerator <Arrow/></Link></div><div className="roadmap-ui"><header><span>Scale roadmap</span><b>68% complete</b></header>{[["Foundation","Operating model installed","Complete"],["Intelligence","Executive signals live","Complete"],["Growth","Distribution engine","Active"],["Capital","Investor readiness","Next"]].map((r,i)=><div className="roadmap-line" key={r[0]}><i>{i+1}</i><span><b>{r[0]}</b><small>{r[1]}</small></span><em>{r[2]}</em></div>)}</div></article></section>

  <section className="cf-results"><div className="results-copy"><span className="cf-section-no">04 / OUTCOMES</span><h2>Real systems.<br/>Real movement.</h2><p>We define success before the build and measure the operating result after it.</p><Link href="/case-studies" className="cf-btn light">View client stories <Arrow/></Link></div><div className="result-grid">{outcomes.map((o,i)=><article key={o[0]}><small>0{i+1}</small><b>{o[0]}</b><span>{o[1]}</span></article>)}</div></section>

  <section className="cf-final"><div className="final-orb"><GlobeScene/></div><div><span className="cf-section-no">YOUR NEXT MOVE</span><h2>Find the constraint.<br/>Multiply what works.</h2><p>Start with a focused assessment of your operations, AI readiness, and highest-leverage opportunity.</p><Link href="/assessment" className="cf-btn light">Get your AI scale assessment <Arrow/></Link></div></section>
  <footer className="cf-footer"><div><Link href="/" className="cf-logo"><i>I</i>IAN</Link><h2>Turn traction into intelligent scale.</h2></div><div className="footer-nav"><div><b>Explore</b><Link href="/method">Method</Link><Link href="/case-studies">Results</Link><Link href="/insights">Insights</Link></div><div><b>Programs</b><Link href="/accelerator">Accelerator</Link><Link href="/venture-studio">Venture studio</Link><Link href="/6frame-ai-studio">6Frame studio</Link></div><div><b>Company</b><Link href="/about">About</Link><Link href="/privacy">Privacy</Link><Link href="/terms">Terms</Link></div></div><small>© 2026 IAN GROUP · AI EXECUTION FOR COMPANIES WITH TRACTION</small></footer>
  </main>}
