import type { Metadata } from "next";
import Link from "next/link";

const pages: Record<string, {eyebrow:string; title:string; accent:string; intro:string; sections:{title:string;body:string}[]; cta:string}> = {
  "case-studies": {eyebrow:"CLIENT RESULTS",title:"Proof over",accent:"potential.",intro:"Real operating constraints. Practical systems. Measurable movement in the metrics that matter.",sections:[{title:"+25% revenue in 90 days",body:"A custom financial intelligence tool, operating dashboard, and redesigned pricing system helped a beauty business move beyond its growth plateau."},{title:"1M+ impressions in 30 days",body:"A focused founder-positioning and distribution engine turned expertise into market visibility and qualified inbound opportunity."},{title:"8-figure exit support",body:"Strategic positioning, partnerships, visibility, and fundraising support helped compress the path from traction to a successful outcome."}],cta:"Discuss your constraint"},
  "case-studies/studio-salon": {eyebrow:"THE STUDIO SALON / CASE 01",title:"More revenue.",accent:"Two days back.",intro:"How an intelligence layer, better pricing, and operating visibility helped a growing beauty business unlock founder freedom.",sections:[{title:"The ceiling",body:"Revenue had plateaued. The owner worked six days a week, with limited visibility into performance and no reliable path to scale."},{title:"What IAN built",body:"A custom AI financial model, real-time operating dashboard, optimized service structure, and a decision system the team could use every day."},{title:"The result",body:"Revenue increased 25% in 90 days. Owner workload fell from six days to four. Operating costs later declined by more than 40%, while the AI tool delivered a measured 10× return."}],cta:"Build your leverage system"},
  "method": {eyebrow:"THE FORCE MULTIPLIER METHOD™",title:"From friction",accent:"to flow.",intro:"A business-first system for turning AI possibility into operating leverage and measurable growth.",sections:[{title:"01 — Diagnose",body:"Map economics, workflows, data, decisions, and founder dependencies to isolate the constraint that matters most."},{title:"02 — Design",body:"Create a prioritized blueprint connecting use cases to business outcomes, owners, safeguards, and adoption."},{title:"03 — Build",body:"Integrate the stack, deploy the system, redesign the workflow, document the model, and train the team."},{title:"04 — Multiply",body:"Measure the lift, optimize adoption, and extend the system into the next highest-leverage area."}],cta:"Start with a diagnosis"},
  "services/operational-leverage": {eyebrow:"OPERATIONAL LEVERAGE",title:"Make your business",accent:"think and move.",intro:"Connected data, AI agents, intelligent workflows, and decision systems designed around how your company actually operates.",sections:[{title:"AI systems & agents",body:"Purpose-built assistants and agents that handle repeatable, multi-step work inside clear human guardrails."},{title:"Workflow automation",body:"Redesigned processes that connect your existing tools, remove re-entry, and make exceptions visible."},{title:"Operational intelligence",body:"Live dashboards and decision signals that turn fragmented information into timely action."}],cta:"Map your highest-value workflow"},
  "services/growth-leverage": {eyebrow:"GROWTH LEVERAGE",title:"Turn expertise",accent:"into attention.",intro:"Positioning, content systems, partnerships, and founder-led distribution built to compound—not disappear between campaigns.",sections:[{title:"Strategic positioning",body:"A sharp market narrative connecting your authority, customer problem, and differentiated point of view."},{title:"6Frame AI Studio",body:"An AI-enabled creative pipeline for premium content, campaigns, decks, and founder media."},{title:"Distribution systems",body:"Repeatable publishing, partnership, and visibility motions connected to qualified business outcomes."}],cta:"Build your growth engine"},
  "accelerator": {eyebrow:"IAN ACCELERATOR",title:"Speed to scale for",accent:"founders with traction.",intro:"Direct operator access, strategic partnerships, visibility, and fundraising support for companies ready to move.",sections:[{title:"Who it is for",body:"Revenue-generating startups with a strong product, a visible plateau, and the ambition to execute at a new level."},{title:"What you get",body:"Senior advisory, ecosystem access, a visibility campaign, operating support, and a focused plan for capital readiness."},{title:"What we expect",body:"Candor, evidence of traction, fast decision-making, and real commitment to the work—not passive mentorship."}],cta:"Apply to the accelerator"},
  "venture-studio": {eyebrow:"IAN VENTURE STUDIO",title:"Build the company",accent:"behind the idea.",intro:"A hands-on venture model connecting market strategy, product intelligence, operating systems, and an ecosystem built for velocity.",sections:[{title:"Validate",body:"Pressure-test the market, economics, and wedge before complexity hardens around the idea."},{title:"Venture-build",body:"Shape the product, operating model, narrative, and go-to-market system alongside experienced operators."},{title:"Scale or exit",body:"Prepare for distribution, partnerships, capital, and the operational maturity the next stage demands."}],cta:"Bring us the opportunity"},
  "6frame-ai-studio": {eyebrow:"6FRAME AI STUDIO",title:"Creative velocity.",accent:"Human taste.",intro:"An AI-enabled studio for brands and founders who need more output without lowering the bar.",sections:[{title:"Founder media",body:"Distinctive short-form, thought leadership, and campaign systems built around a credible point of view."},{title:"Launch creative",body:"Narrative, visual systems, decks, social assets, and launch moments designed as one coherent experience."},{title:"Content operations",body:"A repeatable pipeline for ideation, production, approval, distribution, and performance learning."}],cta:"Build your creative system"},
  "about": {eyebrow:"ABOUT IAN",title:"Operators building",accent:"leverage.",intro:"IAN brings strategy, AI implementation, operating design, and growth execution into one senior team.",sections:[{title:"Business first",body:"We start with economics, decisions, and workflow reality—not a predetermined technology stack."},{title:"In the work",body:"The people who shape the strategy remain close through build, adoption, and measurement."},{title:"Built to transfer",body:"Clients keep the knowledge. Systems include ownership, documentation, safeguards, and team enablement."}],cta:"Meet IAN in a working session"},
  "insights": {eyebrow:"FIELD NOTES",title:"Intelligence for",accent:"companies in motion.",intro:"Practical thinking on AI economics, operating leverage, founder dependency, and the systems behind sustainable scale.",sections:[{title:"The founder dependency audit",body:"Five signals that growth is still waiting on you—and how to redesign the decision flow."},{title:"AI agents vs. automation",body:"A practical guide to choosing the right level of intelligence for the workflow in front of you."},{title:"Why pilots die after the demo",body:"The operating, data, and adoption decisions that separate an impressive prototype from durable value."}],cta:"Get the operator briefing"},
  "assessment": {eyebrow:"AI SCALE ASSESSMENT",title:"Find the constraint.",accent:"Multiply what works.",intro:"A focused 30-minute working session to identify your highest-leverage bottleneck and the smartest next move.",sections:[{title:"Before the call",body:"Share your stage, current systems, biggest operating constraint, and what a meaningful result would look like."},{title:"In the session",body:"We map the constraint, readiness, priority use case, likely economics, and the decisions required to move."},{title:"What you leave with",body:"A clear constraint map, readiness signal, priority opportunity, and an honest recommendation—even if IAN is not the right fit."}],cta:"Request your assessment"},
};

export async function generateMetadata({params}:{params:Promise<{slug:string[]}>}):Promise<Metadata>{const {slug}=await params;const p=pages[slug.join("/")];return {title:p?.title.replace(/\.$/,"")||"IAN Group",description:p?.intro||"AI execution for companies with traction."}}

export default async function DetailPage({params}:{params:Promise<{slug:string[]}>}){const {slug}=await params;const key=slug.join("/");const p=pages[key];if(!p)return <main className="detail"><Link href="/" className="detail-brand">IAN</Link><section className="detail-hero"><p>404 / SIGNAL LOST</p><h1>This path<br/><em>doesn’t exist.</em></h1><Link href="/" className="button primary">Return home ↗</Link></section></main>;return <main className="detail"><header className="detail-header"><Link href="/" className="detail-brand"><i>I</i>IAN</Link><Link href="/" className="detail-back">← Back to overview</Link><Link href="/assessment" className="detail-contact">Get assessed ↗</Link></header><section className="detail-hero"><p>{p.eyebrow}</p><h1>{p.title}<br/><em>{p.accent}</em></h1><div className="detail-intro">{p.intro}</div></section><section className="detail-sections">{p.sections.map((s,i)=><article key={s.title}><span>0{i+1}</span><h2>{s.title}</h2><p>{s.body}</p></article>)}</section><section className="detail-cta"><p>NEXT / MOVE</p><h2>{p.cta}</h2><Link href="/assessment" className="button primary">Start the conversation ↗</Link></section><footer className="detail-footer"><Link href="/">IAN GROUP</Link><span>AI EXECUTION FOR COMPANIES WITH TRACTION</span><span>© 2026</span></footer></main>}
